name: Linux Build

on:
  push:
    branches:
      - master
      - dev

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: sudo apt install...
      run: sudo apt install ninja-build libasound2-dev mesa-utils libx11-dev xorg-dev libglu1-mesa-dev freeglut3-dev libglew1.5 libglew1.5-dev libglu1-mesa libglu1-mesa-dev libgl1-mesa-glx libgl1-mesa-dev
    - name: cd subprojects/luajit && make
      run: cd subprojects/luajit && make
    - name: mkdir build
      run: mkdir build
    - name: cd build && cmake .. -GNinja
      run: cd build && cmake .. -GNinja
    - name: cd build && ninja
      run: cd build && ninja
    - name: cp build/nibble src
      run: cp build/nibble src
    - name: mkdir nibble
      run: mkdir nibble
    - name: cp build/nibble nibble
      run: cp build/nibble nibble
    - name: cp src/{apps,frameworks} nibble
      run: cp -r src/{apps,frameworks} nibble
    - uses: actions/upload-artifact@master
      with:
        name: Nibble for Linux (x64)
        path: nibble/
